// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vegjvkykohtvjwtwvpfd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZlZ2p2a3lrb2h0dmp3dHd2cGZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1NjkyOTAsImV4cCI6MjA1OTE0NTI5MH0.ryzcUojxUGl3ZQAQtyvbXOXFghICby9PrraIZ160I8o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});